
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ConvexClientProvider } from "./ConvexClientProvider";
import { Toaster } from "@/components/ui/sonner";
import { FilesContextProvider } from "./_context/FilesListContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Inkbliss",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ConvexClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > 
            <FilesContextProvider>
            {children}
            </FilesContextProvider>
            <Toaster richColors/>
          </ThemeProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
